version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
    versioning-strategy: increase
    groups:
      minors-and-patches:
        applies-to: version-updates
        patterns: ["*"]
        update-types: ["minor", "patch"]
      majors:
        applies-to: version-updates
        patterns: ["*"]
        update-types: ["major"]

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    groups:
      minors-and-patches:
        applies-to: version-updates
        patterns: ["*"]
        update-types: ["minor", "patch"]
      majors:
        applies-to: version-updates
        patterns: ["*"]
        update-types: ["major"]
